### ISSUE TITLE
SWC file not properly displayed

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.model.swc#6]
We are trying to load [this swc file](http://neuromorpho.org/neuron_info.jsp?neuron_name=dCH-cobalt) using the model interpreter.

This is how it looks using Geppetto (within [OSB](http://127.0.0.1:3000/projects/neuromorpho)):
![screenshot from 2016-02-17 16 35 10](https://cloud.githubusercontent.com/assets/6850223/13116827/55276d1e-d595-11e5-8091-c720f33a341c.png)
![screenshot from 2016-02-17 16 35 29](https://cloud.githubusercontent.com/assets/6850223/13116829/57d514b2-d595-11e5-98f0-7bcfe5d53c21.png)

and this is how it looks using the neuromorpho visualiser (applet)
![selection_053](https://cloud.githubusercontent.com/assets/6850223/13116859/7ee917a6-d595-11e5-8584-51c2206ac976.png)
![selection_052](https://cloud.githubusercontent.com/assets/6850223/13116863/81d8092c-d595-11e5-9171-05ce747d52b2.png)

Seems to be something wrong...

cc @tarelli

**Comment by tarelli** [comment]
@adrianq Spheres appear when points are marked as soma. Whether or not that is a good idea depends on how the soma tag was used to begin with, i.e. for one point vs for many points.

**Comment by adrianq** [comment]
and that line that can be seen parallel to the spheres? cc @pgleeson

**Comment by tarelli** [comment]
I don't know about that, hasn't happened with any of the other files we loaded, somebody needs to debug it.

**Comment by Robbie1977** [comment]
They have allocated all segments they consider 'soma' as 1 and hence no lines.

I'll take a look at modifying the handling of 'soma' so they only draw a sphere if the parent is -1

**Comment by Robbie1977** [comment]
Should be resolved in #10

**Comment by tarelli** [comment]
@adrianq can you test when you got a chance? thx!

**Comment by LordKrabo** [comment]
@adrianq @tarelli Can I move this to the next milestone (spring 74)? Cheers.

**Comment by tarelli** [comment]
@LordKrabo Let's assign it to 75 as "needs review", Adrian is on holiday right now, once he's back he can check Rob's fix!

**Comment by Robbie1977** [comment]
@adrianq can this be closed now?

**Comment by adrianq** [comment]
The good old times :) I have tried to test it in OSB but this model doesn't seem to work. 
![screenshot from 2017-04-17 20 18 07](https://cloud.githubusercontent.com/assets/6850223/25101168/102c40ee-23ab-11e7-8b8e-56fe0ab946d1.png)

Probably the error has to do with OSB and not with the SWC model interpreter... Maybe @mattearnshaw or @pgleeson can throw some light on this?

**Comment by tarelli** [comment]
Working now
![screen shot 2017-10-20 at 10 06 45](https://user-images.githubusercontent.com/81127/31813476-6b2c506e-b57e-11e7-99a7-975689a5b764.png)
